### ISSUE TITLE
Just a couple questions,

### ISSUE THREAD

**Issue by mattos123** [m4tuzalix/The-crims---selenium-robbery-bot#1]
how can i run this on windows? i've been trying to install selenium , got installed, and still cant run the python script., where can i get an full install instruction ?

**Comment by mattos123** [comment]
```
Traceback (most recent call last):
  File "assassult.py", line 187, in <module>
    app = crims_robber(login, password)
  File "assassult.py", line 33, in __init__
    self.assassult()
  File "assassult.py", line 80, in assassult
    stamina_cost = last.index("-")
AttributeError: 'NoneType' object has no attribute 'index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "assassult.py", line 193, in <module>
    app = crims_robber(login, password)
  File "assassult.py", line 33, in __init__
    self.assassult()
  File "assassult.py", line 62, in assassult
    current_toxic = self.browser.find_element_by_xpath('//div[@class="user_profile_progressbar progressbar"]//div[@id="addiction-progressbar"]').value_of_css_property("width")
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="user_profile_progressbar progressbar"]//div[@id="addiction-progressbar"]"}
  (Session info: chrome=78.0.3904.108)
```

**Comment by mattos123** [comment]
bot isnt working after round 114

**Comment by jrodrigues1994** [comment]
mattos123, entre em contato comigo pelo wpp (21)99851-8006
