### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zoiodelula** [m4tuzalix/The-crims---selenium-robbery-bot#7]
Traceback (most recent call last):
  File "C:\Users\Raphael PC\Downloads\The-crims---selenium-robbery-bot-master\The-crims---selenium-robbery-bot-master\2023\main.py", line 1, in <module>
    from utils.connector import Connector
  File "C:\Users\Raphael PC\Downloads\The-crims---selenium-robbery-bot-master\The-crims---selenium-robbery-bot-master\2023\utils\connector.py", line 2, in <module>
    from utils.html_elements import ElementFinder
  File "C:\Users\Raphael PC\Downloads\The-crims---selenium-robbery-bot-master\The-crims---selenium-robbery-bot-master\2023\utils\html_elements.py", line 14, in <module>
    ELEMENT_TYPE = WebElement | List[WebElement] | None
TypeError: unsupported operand type(s) for |: 'ABCMeta' and '_GenericAlias'

And another point, this bot is not avoiding the log systens?

**Comment by tmcruz94** [comment]
did you extract everything from the zip? Here is working fine
